### ISSUE TITLE
Setup Socials

### ISSUE THREAD

**Issue by cowboy0x** [nearorbit/protocol#2]
**Tasks**

- [ ] Setup domain (30min)[cowboy]
- [ ] Setup Discord Channel (30min) [galactica]
    - [ ] Onboarding Story - 'A journey through space', add image, create channels, ensure every team member is in discord with their anon name/account (don't join with your reg account)
- [ ] Setup Twitter (30min) [cowboy]
    - [ ] Set date for first AMA and create a plan around it
- [ ] Setup Forum (discourse) (4hr) [galactica]
    - [ ] Configure domain-
    - [ ] Configure Mailgun
    - [ ] Create VM and install discourse
    - [ ] https://www.entechlog.com/blog/kafka/how-to-install-discourse-in-aws-lightsail/
- [ ] Setup landing page (4hr) [cowboy]
    - [ ] Hero section
    - [ ] About section
    - [ ] Socials Links
    - [ ] App link (Hidden for now)
    - [ ] Configure domain
- [ ] Setup docs (4hrs) [cowboy]
    - [ ] Remove any names/mentions, cleanup existing docs

Estimation: 12.5 hrs
Deadline: Friday April 1st, 2022

cowboy: 8hrs
galactica: 4.5hrs
shah: 0 hrs
